http:
  config:
    conn-max-total: 20
    max-per-route: 20
    time-to-live: 60
    connect-timeout: 2000
    keep-alive-time: 30
    connect-request-timeout: 2000
    socket-timeout: 2000
user:
  appId: yuYsd0cOYKyWGbRO
spring:
  redis:
    host: 140.143.251.72
    password: stythm950829