server:
  port: 8021
spring:
  application:
    name: provider
  rabbitmq:
    host: 114.115.154.105
    port: 5672
    username: admin
    password: admin123456
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated