wx:
  AppID: wx8870986258c76de4
  AppSecret: 322c2aac0350d2aff2378f565a02f813
  Token: stoneh
httpclient:
  config:
    enableProxy: false
    # 代理的host
    proxyHost: 127.0.0.1
    # 代理端口
    proxyPort: 80
    # 连接超时或异常重试次数
    retryTime: 3
    # 长连接保持时间，单位为s
    keepAliveTime: 30
    # 连接池最大连接数
    connMaxTotal: 20
    maxPerRoute: 20
    # 连接超时时间，单位ms
    connectTimeout: 2000
    # 请求超时时间
    connectRequestTimeout: 2000
    # sock超时时间
    socketTimeout: 2000
    # 连接存活时间，单位s
    timeToLive: 60